# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160312_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default=b'Aleko', max_length=128),
        ),
    ]
