# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 13:56
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160313_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('addr', models.CharField(db_index=True, default='', max_length=256)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'verbose_name': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-modify_date'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='addr',
            field=models.CharField(db_index=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Aleko', max_length=128),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ManyToManyField(to='blog.BlogCategory'),
        ),
    ]
