# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160324_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='article_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
