# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 12:49
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160427_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='Summary'),
        ),
    ]
